server:
  port: 8888



logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          # uri: file://${user.home}/git/selamino-services/config-server-repository
          uri: https://github.com/bereketdeb/config-server-repo.git
          default-label: main
          username: bereketdeb
          password:
          #password: '{cipher}b2019336b24b5e76c45708c68a73efab12fc84256f0463c0dcdbcae67a45ff7e1856e3173f186c0503182aa27e01682fc8d7c82fde6bc2ed80691ad5980cc858'
          #password: ATBB2S6AVKUfQ2AMkqrcVUwBsU3BF7A473F4
          clone-on-start: true
    #        bootstrap: true
    #      enabled: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      #password: password
      password: '{cipher}603c630265ab85aed6fa9449aff1cc7c409374bdb49d4e9d03bdb91b4cfca885f564ff7a42f69875a996a93180d34462'



